"""
Script that plots the force_displacement data generated by rob_controls force_displacement testing

data format:
linenum date/time [x,y,z] [force_x,force_y,force_z,force_Rx,force_Ry,force_Rz]


It will plot the position, forces, velocity and acceleration

"""

import matplotlib.pyplot as plt
from tools import *


#Organise the plotting
def main(filepath):

    datetimes = []
    pos = []
    forces = []



    #Open the file
    with open(filepath) as file:
        #Go through every line
        for line in file:
            #Ensure line is empty
            if line:
                #Split the line up
                tokens = data_split(line)         
                
                #Append the time data
                datetimes.append(tokens[0])

                #Append the position data
                pos.append(tokens[1])
                
                #Append the force data
                forces.append(tokens[2])


    #Calculate the time differences 
    time = calc_time_passed(datetimes)

    #Turn the positions into numbers
    pos = str_to_array(pos)
   

    #Turn the forces into numbers
    force = str_to_array(forces)


    #Check that the data arrays are the same lengths
    if(not len(time) == len(pos) == len(forces)):
        print("DATA ARRAYS ARE INCONSISTENT LENGTH")
        raise Exception()
    

    #Calculate the velocities
    vels = xyz_integ_avg(time, pos)   


    #Calculate the accelerations
    accs = xyz_integ_avg(time, three_arrs_to_threeD(vels[0], vels[1], vels[2]))

  
    #Create subfigure array for plots
    #We want to plot force vs pos?
    #Can decide later

    
    plot_force(force, time)
    #plot_pos(pos, time)
    return


#Split the line up
#Not the most efficient but thats okay for now 
def data_split(line):

    tokens = []

    #Can remove the line number
    line = line[line.find(",") + 1:]

    #Can remove the date - will always be same length
    DATE_LENGTH = 11
    line = line[DATE_LENGTH:]

    #Save the time
    tokens.append(line[:line.find(",")])

    #Remove the time 
    line = line[line.find(",") + 1:]

    #Save the positions
    tokens.append(line[:line.find("]") + 1])
    #Save the forces
    tokens.append(line[line.find("]") + 2:line.find("\n")])    

    return tokens



#Plot the  x vs y pos vs force
def plot_force(force, time):


    #Create force array contianing data of each axes
    forces  = [[],[],[],[],[],[]]

    """
    for i in force:
        forces[0].append(abs(i[0]))
        forces[1].append(abs(i[1]))
        forces[2].append(abs(i[2]))
        forces[3].append(abs(i[3]))
        forces[4].append(abs(i[4]))
        forces[5].append(abs(i[5]))
    """
    for i in force:
        forces[0].append(i[0])
        forces[1].append(i[1])
        forces[2].append(i[2])
        forces[3].append(i[3])
        forces[4].append(i[4])
        forces[5].append(i[5])


    fig, ax1 = plt.subplots()

    ax1.set_xlabel("Time (S)")
    ax1.set_ylabel("|Force| (N)")
    
    ax1.plot(time, forces[0],  label = "$F_x$", color="red")
    ax1.plot(time, forces[1],  label = "$F_y$", color="green")
    ax1.plot(time, forces[2],  label = "$F_z$", color="blue")

    ax2 = ax1.twinx()
    ax2.set_ylabel("Moment (N/m)")
    
    ax2.plot(time, forces[3],  label = "$M_x$", color="darkorange", linestyle="dashed", linewidth = "0.5")
    ax2.plot(time, forces[4],  label = "$M_y$", color="navy", linestyle="dashed", linewidth = "0.5")
    ax2.plot(time, forces[5],  label = "$M_z$", color="cyan", linestyle="dashed", linewidth = "0.5")
    
    
    fig.legend()


    plt.show()


def plot_pos(pos, time):

    x = [i[0] for i in pos]
    y = [i[1] for i in pos]


    plt.plot(x[10:], y[10:])

    plt.xlabel("x (mm)")
    plt.ylabel("y (mm)")

    plt.show()


    return





if __name__ == "__main__":
    print("FORCE DISPLACEMENT PLOTTING ------------------")

    filepath = "C:/Users/User/Documents/Results/first_pass_test/raw/first_real_run.txt"

    main(filepath)