"""
Script that plots the force_displacement data generated by rob_controls force_displacement testing

data format:
linenum date/time [x,y,z] [force_x,force_y,force_z,force_Rx,force_Ry,force_Rz]


It will plot the position, forces, velocity and acceleration

"""

import matplotlib.pyplot as plt

#Organise the plotting
def main(filepath):

    times = []
    curr_time = 0
    pos = []
    forces = []



    #Open the file
    with open(filepath) as file:
        #Go through every line
        for line in file:
            #Ensure line is empty
            if line:
                #Split the line up
                line.split(",")             

    


    return


#Split the line up
def data_split(line):

    tokens = []

    #Can remove the line number
    line.remove(line.find(","))

    

    return tokens


#Calculate the velocities


#Calculate the accelerations






if __name__ == "__main__":
    print("gello2)")

    filepath = "C:/Users/User/Documents/Results/first_pass_test/raw/test.txt"

    main(filepath)